### PR TITLE
Using scrollpoints with variables

### PR DESCRIPTION
**Pull request by phurytw**
The `scrollpoint` can be set using the directive scope option.
This allows to change the scrollpoint using a variable.

[Sample](http://plnkr.co/3mVnAg0uevzFDr1wy5f2)

You can change the value in the `input` and the scrollpoint will be updated if the entered value is valid.

This is done with a `$watch()` listener. I also changed the block that sets `shift`, `absolute` and `fixLimit` to accept "absolute" values after render and the whole thing is wrapped into a function that is called whenever the `$watch()` event is fired.

### CODE REVIEW

**Comment by PowerKiKi** [comment]
I'd expect that the class would be toggled accordingly when the scrollpoint value changes. Right now you have to change the value and then scroll to have any effect on the class.

Also please add demo and tests. And do not include a release in a PR.

**Comment by phurytw** [comment]
Fixed :ok_hand:

I also added a demo and a test.

**Comment by PowerKiKi** [comment]
Great, could you please [squash commits](http://stackoverflow.com/a/5201642/37706) into only one and force push ? Then i'll merge.

**Comment by phurytw** [comment]
Done !

**Comment by PowerKiKi** [comment]
Released as 1.2.0

**Pull request merged**
