### PR TITLE
refactoring ui-scrollpoint structure

### PR DESCRIPTION
**Pull request by plong0**
- rebuilt ui-scrollpoint using extendable controller
- redesigned demo
- replaced ui-scrollpoint-bottom with configurable ui-scrollpoint-edge

added element.ready(function({ })) wrappers in unit tests

**Important Changes**
- replace `ui-scrollpoint-bottom` with `ui-scrollpoint-edge="bottom"`
- `ui-scrollpoint-action` callback parameters reversed
  - old: `function(element, distance)`
  - new: `function(distance, element, edge)`

**Enhancements**
- `edge` parameter for action callbacks - `"top"` or `"bottom"` depending which edge of the target the scrollpoint hit
- multiple edges per scrollpoint.
  - ex. `ui-scrollpoint-edge="['top','bottom']"` to trigger when scrollpoint hits top or bottom of its target
- mapping edge of screen to edge of element.
  - ex. `ui-scrollpoint-edge="{top: 'bottom'}"` triggers when the bottom of the element hits the top edge of target
-  `ui-scrollpoint-edge="view"` to trigger when element scrolls out of view (equivalent to `ui-scrollpoint-edge="{top: 'bottom', bottom: 'top'}"`

### CODE REVIEW

**Comment by plong0** [comment]
I have the `ui-scrollpoint-pin` directive on a separate branch.  It's ready to merge in here, but I'm not sure if it would be out of the scope of this project.  I could set it up as a separate component if we don't want it in the core ui-scrollpoint module.

**Comment by karptonite** [comment]
See issue #12 . I tried out this refactored branch as well, and had the same failure. I'm excited about all the new features, once we can get the core functionality back on track.

**Comment by plong0** [comment]
Latest commit addresses issue #12

**Comment by karptonite** [comment]
Great! I'll give it a try.

**Comment by plong0** [comment]
I posted a few notes about position: fixed; / sticky elements / pinning feature in #12.

**Comment by karptonite** [comment]
I can confirm that it works now. I hope this is merged soon so that the head is no longer bugged. :+1:

**Comment by karptonite** [comment]
@PowerKiKi just wanted to draw your attention to the fact that a substantial bug (#12) was introduced in the 1.2.1 release, and seems to be fixed by this pull request.

**Comment by PowerKiKi** [comment]
Thanks ! Releasing as 2.0.0 since there is a BC break.

**Comment by plong0** [comment]
Just wanted to note that I have set up a `ui-scrollpoint-pin` component at https://github.com/TechNaturally/ui-scrollpoint-pin

**Pull request merged**
